-- CREATE DATABASE taskdb

-- CREATE TABLE task(
--     id SERIAL PRIMARY KEY,
--     title VARCHAR(255) UNIQUE,
--     description VARCHAR(255)
-- );

/*ACÁ HE CREADO MI BASE DE DATOS, PERO EL MEN DEL VIDEO USA LA TERMINAL, Y CUANDO QUIERA USAR ALGO DE LA BASE DE DATOS ME SALE QUE NO LA TENGO CREADA*/